### ISSUE TITLE
Data issues

### ISSUE THREAD

**Issue by DailyCovidCases** [Sandbird/covid19-Greece#6]
ECDC report from Monday to Sunday each week. Why do you only update on Thursdays?
[cases-greece-fixed.csv](https://github.com/Sandbird/covid19-Greece/files/13602678/cases-greece-fixed.csv)

**Comment by Sandbird** [comment]
Our National Public Health Organization (NPHO), as per its new established protocol (also noted in the README.md), releases the weekly health report every Thursday. Actually, the latest report was published a few hours ago on their official website (https://eody.gov.gr) (https://eody.gov.gr/wp-content/uploads/2023/12/ekthesi-epitirisis-anapneustikon-ion-2023-48.pdf).
Since it doesn't include the new weekly cases, I have to wait a couple of days for the ECDC report to come out in order to complete the dataset. Once that happens, I update the 'cases_weekly_ecdc.csv' file, which contains both the NPHO report and the ECDC corrections.

![Screenshot_1](https://github.com/Sandbird/covid19-Greece/assets/204934/e4f7ee77-3737-492e-a516-22fa421832ca)

**Comment by Sandbird** [comment]
ECDC just stopped reporting...

**Comment by Sandbird** [comment]
21-12-2023

cases.csv, cases_weekly_ecdc.csv: Every Thursday afternoon, I will update both files with the latest EODY updates. This means that the 'new_cases', 'confirmed' values will encompass both new cases and reinfections. When the ECDC report is released, the values will be adjusted accordingly. This adjustment will also apply to the 'reinfections' values. In general, if you encounter a 0 value in the reinfections column, it indicates that the ECDC report has not been released yet.
